In [1]:
import pandas as pd

In [3]:
crop_prod = pd.read_csv("../data/crop_production.csv")
all_ind = pd.read_csv("../data/all_india.csv")
dist_rain = pd.read_csv("../data/district wise rainfall normal.csv")
rain_ind = pd.read_csv("../data/rainfall in india 1901-2015.csv")

CROP Production Data

In [7]:
crop_prod.describe()

           Crop_Year          Area    Production
count  246091.000000  2.460910e+05  2.423610e+05
mean     2005.643018  1.200282e+04  5.825034e+05
std         4.952164  5.052340e+04  1.706581e+07
min      1997.000000  4.000000e-02  0.000000e+00
25%      2002.000000  8.000000e+01  8.800000e+01
50%      2006.000000  5.820000e+02  7.290000e+02
75%      2010.000000  4.392000e+03  7.023000e+03
max      2015.000000  8.580100e+06  1.250800e+09

In [ ]:
crop_prod.isnull().sum() # prodcolumn has null value

State_Name          0
District_Name       0
Crop_Year           0
Season              0
Crop                0
Area                0
Production       3730
dtype: int64

Checking incosisteance in categorical data

In [17]:
crop_prod.dtypes

State_Name           str
District_Name        str
Crop_Year          int64
Season               str
Crop                 str
Area             float64
Production       float64
dtype: object

In [30]:
crop_prod.duplicated().sum()

np.int64(0)

In [23]:
string_cols = crop_prod.select_dtypes(include=['object','string']).columns
for i in string_cols:
    inconsistent_value =crop_prod[i]!=crop_prod[i].str.strip()
    inconsistent_value=crop_prod[inconsistent_value][i].unique()
    if len(inconsistent_value) > 0:
        print(f"Cols {i}")
        print(f"vale {inconsistent_value}")

Cols State_Name
vale <StringArray>
['Jammu and Kashmir ', 'Telangana ']
Length: 2, dtype: str
Cols Season
vale <StringArray>
['Kharif     ', 'Whole Year ', 'Autumn     ', 'Rabi       ', 'Summer     ',
 'Winter     ']
Length: 6, dtype: str
Cols Crop
vale <StringArray>
['Coconut ']
Length: 1, dtype: str

All INDIA Data preprocessing and data exploration

In [18]:
all_ind.dtypes

state             str
district          str
market            str
commodity         str
variety           str
arrival_date      str
min_price       int64
max_price       int64
modal_price     int64
dtype: object

In [ ]:
all_ind

,state,district,market,commodity,variety,arrival_date,min_price,max_price,modal_price
0,Andaman and Nicobar,South Andaman,Port Blair,Amaranthus,Amaranthus,04/03/2019,6000,8000,7000
1,Andaman and Nicobar,South Andaman,Port Blair,Banana - Green,Banana - Green,04/03/2019,4500,5500,5000
2,Andaman and Nicobar,South Andaman,Port Blair,Bhindi(Ladies Finger),Bhindi,04/03/2019,6000,8000,7000
3,Andaman and Nicobar,South Andaman,Port Blair,Bitter gourd,Other,04/03/2019,6000,8000,7000
4,Andaman and Nicobar,South Andaman,Port Blair,Black pepper,Other,04/03/2019,110000,130000,120000
...,...,...,...,...,...,...,...,...,...
2233,West Bengal,Uttar Dinajpur,Islampur,Potato,Jyoti,04/03/2019,530,570,550
2234,West Bengal,Uttar Dinajpur,Islampur,Rice,Other,04/03/2019,3550,3650,3600
2235,West Bengal,Uttar Dinajpur,Raiganj,Jute,TD-5,04/03/2019,4400,4600,4500
2236,West Bengal,Uttar Dinajpur,Raiganj,Rice,Other,04/03/2019,3450,3550,3500
2237,West Bengal,Uttar Dinajpur,Raiganj,Wheat,Kalyan,04/03/2019,2075,2125,2100

In [ ]:
all_ind.isnull().sum() # no null values

state           0
district        0
market          0
commodity       0
variety         0
arrival_date    0
min_price       0
max_price       0
modal_price     0
dtype: int64

In [ ]:
# duplicate exists
all_ind.duplicated().sum()

np.int64(2)

In [ ]:
ind_col = all_ind.select_dtypes(include=['str']).columns
for cols in ind_col:
    in_value = all_ind[cols] != all_ind[cols].str.strip()
    in_value = all_ind[in_value][cols].unique()
    if len(in_value) > 0:
        print(f" COl {cols}")
        print(f"vales{in_value}") # one column with inconsitent data

 COl variety
vales<StringArray>
[' Subabul']
Length: 1, dtype: str